apiVersion: v1
kind: Service
metadata:
  name: {{ include "panic.fullname" . }}-api
  labels:
    {{- include "panic.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  selector:
    app.kubernetes.io/name: {{ include "panic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api
  ports:
    - name: http
      port: 80
      targetPort: 8080