apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "panic.fullname" . }}-api
  labels:
    {{- include "panic.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "panic.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api
  template:
    metadata:
      labels:
        {{- include "panic.labels" . | nindent 8 }}
        app.kubernetes.io/component: api
    spec:
      serviceAccountName: {{ default (include "panic.fullname" .) .Values.serviceAccount.name }}
      containers:
        - name: api
          image: "{{ .Values.images.api.repository }}:{{ .Values.images.tag }}"
          imagePullPolicy: {{ .Values.images.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "panic.fullname" . }}-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.storage.postgres.dsnSecretName }}
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.builtin.jwtSecretName }}
                  key: JWT_SECRET
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet: { path: /healthz, port: 8080 }
          readinessProbe:
            httpGet: { path: /readyz, port: 8080 }
          resources:
            {{- toYaml .Values.resources.default | nindent 12 }}