{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "panic.fullname" .) .Values.serviceAccount.name }}
  labels:
    {{- include "panic.labels" . | nindent 4 }}
{{- end -}}