apiVersion: v1
kind: Service
metadata:
  name: {{ include "panic.fullname" . }}-ui
  labels:
    {{- include "panic.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui
spec:
  selector:
    app.kubernetes.io/name: {{ include "panic.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: ui
  ports:
    - name: http
      port: 80
      targetPort: 3000
